### ISSUE TITLE
How to start the ripple from an angle

### ISSUE THREAD

**Issue by brainvision** [skyfishjy/android-ripple-background#2]
Hi I'm using your beatufil library on a button that is placed on the lower right angle of the screen: I would like to make the ripple start from that point, but on the contrary I tap on the button and the ripple always start from center..

Thanks a lot..

**Comment by Alok-Sharma** [comment]
I was not able to change the center of the ripple using any layout parameters as suggested by @skyfishjy above. Using the `setX()` and `setY()` methods did change the center, however, the ripples were being clipped when they reached somewhere in he middle. @brainvision were you able to solve this issue?
@skyfishjy it would be awesome if you could provide parameters to set the center of the ripple.

**Comment by Alok-Sharma** [comment]
Just found a solution. To prevent the clipping, set `android:clipChildren="false"` in the parent layout of the `RippleBackground`.

**Comment by hzw1199** [comment]
@Alok-Sharma Thank you so much for sharing !
