### ISSUE TITLE
rippleStrokeWidth parameter not working

### ISSUE THREAD

**Issue by ingeniwi** [skyfishjy/android-ripple-background#7]
Hi,

I am currently implementing this library but it seems that the rippleStrokeWidth parameter is not working.

Here my implementation:

    <com.skyfishjy.library.RippleBackground
					android:layout_width="match_parent"
					android:layout_height="140dp"
					android:layout_marginTop="330dp"
					android:id="@+id/start_content"
					app:rb_color="#000"
					app:rb_radius="42dp"
					app:rb_rippleAmount="5"
					app:rb_type="strokeRipple"
					app:rb_strokeWidth="4dp"
					app:rb_duration="2000"
					app:rb_scale="1.5">

					<ImageView
						android:id="@+id/startButton"
						android:layout_width="84dp"
						android:layout_height="84dp"
						android:layout_centerInParent="true"
						android:src="@drawable/start_button"/>
				</com.skyfishjy.library.RippleBackground>

Any idea why ?

**Comment by michaelbarlow7** [comment]
Having the same issue here.

**Comment by kelib99** [comment]
Some for me. Here is the solution:
Please find this lanes in class RippleBackground.java:
if(rippleType==DEFAULT_FILL_TYPE){
            rippleStrokeWidth=0;
            paint.setStyle(Paint.Style.FILL);
        }else {
            paint.setStyle(Paint.Style.STROKE);
        }
and change it to:
  if(rippleType==DEFAULT_FILL_TYPE){
            rippleStrokeWidth=0;
            paint.setStyle(Paint.Style.FILL);
        }else {
            paint.setStyle(Paint.Style.STROKE);
            paint.setStrokeWidth(rippleStrokeWidth);
        }

**Comment by kelib99** [comment]
Some for me. Here is my solution:
Find this lanes in class `RippleBackground.java`
```java
if(rippleType==DEFAULT_FILL_TYPE){
           rippleStrokeWidth=0;
           paint.setStyle(Paint.Style.FILL);
        }else {
            paint.setStyle(Paint.Style.STROKE);
        }
```
and change it to:
```java
  if(rippleType==DEFAULT_FILL_TYPE){
            rippleStrokeWidth=0;
            paint.setStyle(Paint.Style.FILL);
        }else {
            paint.setStyle(Paint.Style.STROKE);
            paint.setStrokeWidth(rippleStrokeWidth);
        }
```

**Comment by Shivam101** [comment]
This works perfectly !
